In [3]:
#pip install torch

Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch

# 1차원 텐서(=벡터)

In [9]:
t_1d = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t_1d)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t_1d.dim())  # rank. 즉, 차원
print(t_1d.shape)  # shape
print(t_1d.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [11]:
print(t_1d[0], t_1d[1], t_1d[-1])  # 인덱스로 접근
print(t_1d[2:5], t_1d[4:-1])    # 슬라이싱
print(t_1d[:2], t_1d[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


# 2차원 텐서(=행렬)

In [12]:
t_2d = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])

In [13]:
print(t_2d.dim())  # rank. 즉, 차원
print(t_2d.size()) # shape

2
torch.Size([4, 3])


In [21]:
print(t_2d[1, 0]) 
print(t_2d[1, 0].size()) # ↑ 위의 경우의 크기

tensor(4.)
torch.Size([])


In [22]:
print(t_2d[2, 1]) 
print(t_2d[2, 1].size()) # ↑ 위의 경우의 크기

tensor(8.)
torch.Size([])


In [23]:
print(t_2d[2, 2]) 
print(t_2d[2, 2].size()) # ↑ 위의 경우의 크기

tensor(9.)
torch.Size([])


In [17]:
print(t_2d[:, 0]) # 첫번째 차원을 전체 선택한 상황에서 첫번째 차원의 첫번째 것만 가져온다.
print(t_2d[:, 0].size()) # ↑ 위의 경우의 크기

tensor([ 1.,  4.,  7., 10.])
torch.Size([4])


In [18]:
print(t_2d[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t_2d[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [19]:
print(t_2d[:, -1]) # 첫번째 차원을 전체 선택한 상황에서 세번째 차원의 첫번째 것만 가져온다.
print(t_2d[:, -1].size()) # ↑ 위의 경우의 크기

tensor([ 3.,  6.,  9., 12.])
torch.Size([4])


# 브로드캐스팅
## (주의 행렬 간 크기가 달라도 알아서 계산해주므로 오류도 안 난다)

In [24]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


### 행렬 인덱싱, 슬라이싱

In [28]:
print(m1.size())
print(m1.dim())

torch.Size([1, 2])
2


In [31]:
print(m1[:,0])
print(m1[:,1])
print(m2[:,0])
print(m2[:,1])

tensor([3.])
tensor([3.])
tensor([2.])
tensor([2.])


In [32]:
# Vector + scalar(원래 계산 불가)
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3](알아서 스칼라에서 벡터로 변경)
print(m1 + m2)

tensor([[4., 5.]])


#### m1의 크기는 (1, 2) m2의 크기는 (2, 1)였습니다. 이 두 벡터는 원래 수학적으로는 덧셈을 수행할 수 없습니다.
#### 그러나 파이토치는 두 벡터의 크기를 (2, 2)로 변경하여 덧셈을 수행합니다.

In [35]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1.size()) # 1행 2열
print(m2.size()) # 2행 1열
print(m1 + m2)

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


In [ ]:
# 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]

### 행렬 곱셈과 곱셈의 차이(Matrix Multiplication Vs. Multiplication)

- 행렬로 곱셈을 하는 방법은 크게 두 가지가 있습니다. 바로 행렬 곱셈(.matmul)과 원소 별 곱셈(.mul)입니다.
파이토치 텐서의 행렬 곱셈을 보겠습니다. 이는 matmul()을 통해 수행합니다.

In [4]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
#우리가 아는 행렬의 곱(내적)
print('matmul',m1.matmul(m2)) # 2 x 1
#브로드캐스팅으로 차원이 바뀐다
print('mul',m1.mul(m2)) # 2 x 2

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
matmul tensor([[ 5.],
        [11.]])
mul tensor([[1., 2.],
        [6., 8.]])
