In [1]:
import torch

### 평균(Mean)

In [3]:
# 1차원 벡터
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [5]:
# 2차원 행렬
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
4개의 원소의 평균인 2.5
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


##### dim=0이라는 것은 첫번째 차원을 의미합니다. 행렬에서 첫번째 차원은 '행'을 의미합니다. 

##### 인자로 dim을 준다면 해당 차원을 제거한다는 의미가 됩니다. 다시 말해 행렬에서 '열'만을 남기겠다는 의미가 됩니다. 기존 행렬의 크기는 (2, 2)였지만 이를 수행하면 열의 차원만 보존되면서 (1, 2)가 됩니다. 이는 (2,)와 같으며 벡터입니다. 

In [6]:
print(t.mean(dim=0))

tensor([2., 3.])


In [ ]:
# 실제 연산 과정
t.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.

[[1., 2.],
 [3., 4.]]

1과 3의 평균을 구하고, 2와 4의 평균을 구한다.
결과 ==> [2., 3.]

##### 인자로 dim=1을 주겠습니다. 이번에는 두번째 차원을 제거합니다. 즉, 열이 제거된 텐서가 되어야 합니다.

##### 열의 차원이 제거되어야 하므로 (2, 2)의 크기에서 (2, 1)의 크기가 됩니다. 이번에는 1과 2의 평균을 구하고 3과 4의 평균을 구하게 됩니다. 

In [7]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [ ]:
# 실제 연산 결과는 (2 × 1)
[1.5]
[3.5]

##### dim=-1를 주는 경우를 보겠습니다. 이는 마지막 차원을 제거한다는 의미이고, 결국 열의 차원을 제거한다는 의미와 같습니다. 그러므로 위와 출력 결과가 같습니다.

In [9]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


# 덧셈(Sum)

In [14]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print('-'*20)
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print('-'*20)
print(t.sum(dim=0)) # 행을 제거
print('-'*20)
print(t.sum(dim=1)) # 열을 제거
print('-'*20)
print(t.sum(dim=-1)) # 열을 제거

tensor([[1., 2.],
        [3., 4.]])
--------------------
tensor(10.)
--------------------
tensor([4., 6.])
--------------------
tensor([3., 7.])
--------------------
tensor([3., 7.])


# 최대(Max)와 아그맥스(ArgMax)


# 최대(Max)는 원소의 최대값을 리턴하고, 아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴합니다.

In [16]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [17]:
print(t.max()) # Returns one value: max

tensor(4.)


### 행의 차원을 제거한다는 의미이므로 (1, 2) 텐서를 만듭니다. 결과는 [3, 4]입니다.

그런데 [1, 1]이라는 값도 함께 리턴되었습니다. max에 dim 인자를 주면 argmax도 함께 리턴하는 특징 때문입니다. 첫번째 열에서 3의 인덱스는 1이었습니다. 두번째 열에서 4의 인덱스는 1이었습니다. 그러므로 [1, 1]이 리턴됩니다.

In [18]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
