In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [4]:
torch.manual_seed(42)

## y=2x

In [5]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [6]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)

2개의 값이 출력되는데 첫번째 값이 W(tensor([[0.7645]])고, 두번째 값이 b(tensor([0.8300])에 해당됩니다. 두 값 모두 현재는 랜덤 초기화가 되어져 있습니다. 그리고 두 값 모두 학습의 대상이므로 requires_grad=True가 되어져 있는 것을 볼 수 있습니다.

In [7]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7645]], requires_grad=True), Parameter containing:
tensor([0.8300], requires_grad=True)]


In [9]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [12]:
epochs = 2000
for epoch in range(epochs+1):
    
    prediction = model(x_train)
    
    cost = F.mse_loss(prediction,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
         print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, epochs, cost.item()
      ))

Epoch    0/2000 Cost: 3.710179
Epoch  100/2000 Cost: 0.117398
Epoch  200/2000 Cost: 0.072545
Epoch  300/2000 Cost: 0.044828
Epoch  400/2000 Cost: 0.027701
Epoch  500/2000 Cost: 0.017118
Epoch  600/2000 Cost: 0.010578
Epoch  700/2000 Cost: 0.006536
Epoch  800/2000 Cost: 0.004039
Epoch  900/2000 Cost: 0.002496
Epoch 1000/2000 Cost: 0.001542
Epoch 1100/2000 Cost: 0.000953
Epoch 1200/2000 Cost: 0.000589
Epoch 1300/2000 Cost: 0.000364
Epoch 1400/2000 Cost: 0.000225
Epoch 1500/2000 Cost: 0.000139
Epoch 1600/2000 Cost: 0.000086
Epoch 1700/2000 Cost: 0.000053
Epoch 1800/2000 Cost: 0.000033
Epoch 1900/2000 Cost: 0.000020
Epoch 2000/2000 Cost: 0.000013


# 추론

In [13]:
new_var = torch.FloatTensor([4.0])

In [16]:
new_var

tensor([4.])

In [17]:
pred_y = model(new_var)
pred_y

tensor([7.9929], grad_fn=<AddBackward0>)

## W & b 출력

In [18]:
#W의 값이 2에 가깝고, b의 값이 0에 가까운 것을 볼 수 있습니다.
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9959]], requires_grad=True), Parameter containing:
tensor([0.0093], requires_grad=True)]


# 다중 선형 회귀

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [20]:
torch.manual_seed(42)

## 3개의 x로부터 하나의 y를 예측하는 문제입니다.

In [21]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [22]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [24]:
#(5x3)*(3x1)=(5x1)

In [25]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

In [27]:
#첫번째 출력되는 것이 3개의 w고, 두번째 출력되는 것이 b에 해당됩니다. 두 값 모두 현재는 랜덤 초기화가 되어져 있습니다. 그리고 두 출력 결과 모두 학습의 대상이므로 requires_grad=True가 되어져 있는 것을 볼 수 있습니다.


print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1265,  0.1165, -0.2811]], requires_grad=True), Parameter containing:
tensor([0.3391], requires_grad=True)]


In [28]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [29]:
epochs = 2000
for epoch in range(epochs+1):
    # model(x_train)은 model.forward(x_train)와 동일함.
    pred = model(x_train)
    
    cost = F.mse_loss(pred,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, epochs, cost.item()
      ))

Epoch    0/2000 Cost: 38818.851562
Epoch  100/2000 Cost: 3.658000
Epoch  200/2000 Cost: 3.474529
Epoch  300/2000 Cost: 3.300751
Epoch  400/2000 Cost: 3.136089
Epoch  500/2000 Cost: 2.980164
Epoch  600/2000 Cost: 2.832420
Epoch  700/2000 Cost: 2.692471
Epoch  800/2000 Cost: 2.559922
Epoch  900/2000 Cost: 2.434353
Epoch 1000/2000 Cost: 2.315395
Epoch 1100/2000 Cost: 2.202666
Epoch 1200/2000 Cost: 2.095948
Epoch 1300/2000 Cost: 1.994812
Epoch 1400/2000 Cost: 1.899012
Epoch 1500/2000 Cost: 1.808279
Epoch 1600/2000 Cost: 1.722307
Epoch 1700/2000 Cost: 1.640879
Epoch 1800/2000 Cost: 1.563746
Epoch 1900/2000 Cost: 1.490659
Epoch 2000/2000 Cost: 1.421419


In [30]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 

In [31]:
pred_y = model(new_var)
print(pred_y)

tensor([[153.0104]], grad_fn=<AddmmBackward0>)


In [32]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7752, 0.7132, 0.5202]], requires_grad=True), Parameter containing:
tensor([0.3501], requires_grad=True)]
