# 3d Tensor

In [1]:
import torch

In [94]:
z = torch.FloatTensor(
   [
   [[0, 0, 0, 0, 0],
   [50, 50, 50, 50, 50],
   [100, 100, 100, 100, 100],
   [150, 150, 150, 150, 150],
   [0, 0, 0, 0, 0]],
   
   [[10, 10, 10, 10, 10],
   [60, 60, 60, 60, 60],
   [110, 110, 110, 110, 110],
   [160, 160, 160, 160, 160],
   [0, 0, 0, 0, 0]],
   
   [[20, 20, 20, 20, 20],
   [70, 70, 70, 70, 70],
   [120, 120, 120, 120, 120],
   [170, 170, 170, 170, 170],
   [250, 250, 250, 250, 250]],
   ]
   )

In [19]:
print(z)
print(f'{z.dim()}차원입니다.')
print(f'{z.shape[0]}x{z.shape[1]}x{z.shape[-1]}')
print(z.size())

tensor([[[  0.,   0.,   0.,   0.,   0.],
         [ 50.,  50.,  50.,  50.,  50.],
         [100., 100., 100., 100., 100.],
         [150., 150., 150., 150., 150.],
         [  0.,   0.,   0.,   0.,   0.]],

        [[ 10.,  10.,  10.,  10.,  10.],
         [ 60.,  60.,  60.,  60.,  60.],
         [110., 110., 110., 110., 110.],
         [160., 160., 160., 160., 160.],
         [  0.,   0.,   0.,   0.,   0.]],

        [[ 20.,  20.,  20.,  20.,  20.],
         [ 70.,  70.,  70.,  70.,  70.],
         [120., 120., 120., 120., 120.],
         [170., 170., 170., 170., 170.],
         [250., 250., 250., 250., 250.]]])
3차원입니다.
3x5x5
torch.Size([3, 5, 5])


In [72]:
z

tensor([[[  0.,   0.,   0.,   0.,   0.],
         [ 50.,  50.,  50.,  50.,  50.],
         [100., 100., 100., 100., 100.],
         [150., 150., 150., 150., 150.],
         [  0.,   0.,   0.,   0.,   0.]],

        [[ 10.,  10.,  10.,  10.,  10.],
         [ 60.,  60.,  60.,  60.,  60.],
         [110., 110., 110., 110., 110.],
         [160., 160., 160., 160., 160.],
         [  0.,   0.,   0.,   0.,   0.]],

        [[ 20.,  20.,  20.,  20.,  20.],
         [ 70.,  70.,  70.,  70.,  70.],
         [120., 120., 120., 120., 120.],
         [170., 170., 170., 170., 170.],
         [250., 250., 250., 250., 250.]]])

In [95]:
z.mean()

tensor(84.6667)

In [108]:
total = 0
count = 0

for i in range(z.shape[0]):
    for j in range(z.shape[1]):
        for k in range(z.shape[2]):
            total += z[i][j][k]
            count += 1
            
mean = total / count
print(mean)

tensor(84.6667)


## dim=0 5x5

In [20]:
z.mean(dim=0)# 5x5

tensor([[ 10.0000,  10.0000,  10.0000,  10.0000,  10.0000],
        [ 60.0000,  60.0000,  60.0000,  60.0000,  60.0000],
        [110.0000, 110.0000, 110.0000, 110.0000, 110.0000],
        [160.0000, 160.0000, 160.0000, 160.0000, 160.0000],
        [ 83.3333,  83.3333,  83.3333,  83.3333,  83.3333]])

In [34]:
print((0+10+20)/3,(50+60+70)/3,(100+110+120)/3,(150+160+170)/3,(0+0+250)/3)

10.0 60.0 110.0 160.0 83.33333333333333


## dim=1 3x5

In [35]:
z.mean(dim=1)

tensor([[ 60.,  60.,  60.,  60.,  60.],
        [ 68.,  68.,  68.,  68.,  68.],
        [126., 126., 126., 126., 126.]])

In [39]:
print((0+50+100+150+0)/5,(10+60+110+160+0)/5,(20+70+120+170+250)/5)

60.0 68.0 126.0


## dim = 2(=-1) 3x5 

In [36]:
z.mean(dim=-1)

tensor([[  0.,  50., 100., 150.,   0.],
        [ 10.,  60., 110., 160.,   0.],
        [ 20.,  70., 120., 170., 250.]])

In [45]:
test_tensor=torch.zeros(3,5,dtype=float)

In [46]:
test_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [67]:
for i in range(3):
    for j in range(5):
        num=0
        for k in range(5):
            num+=(z[i][j][k])/5
            #print(int(num))
            test_tensor[i][j]=num
test_tensor 

tensor([[  0.,  50., 100., 150.,   0.],
        [ 10.,  60., 110., 160.,   0.],
        [ 20.,  70., 120., 170., 250.]], dtype=torch.float64)

## permute와 transpose

permute()와 transpose()는 유사한 방식으로 작동한다. transpose()는 딱 두 개의 차원을 맞교환할 수 있다. 그러나 permute()는 모든 차원들을 맞교환할 수 있다.

In [81]:
x = torch.rand(16, 32, 3)
print(x.shape)
print(x.dim())


torch.Size([16, 32, 3])
3


In [84]:
y=x.transpose(0,2)
y.shape

torch.Size([3, 32, 16])

In [86]:
z=x.permute(2,1,0)
z.shape

torch.Size([3, 32, 16])

In [8]:
z2

tensor([[[  0,  10,  20],
         [ 50,  60,  70],
         [100, 110, 120],
         [150, 160, 170],
         [  0,   0, 250]],

        [[  0,  10,  20],
         [ 50,  60,  70],
         [100, 110, 120],
         [150, 160, 170],
         [  0,   0, 250]],

        [[  0,  10,  20],
         [ 50,  60,  70],
         [100, 110, 120],
         [150, 160, 170],
         [  0,   0, 250]],

        [[  0,  10,  20],
         [ 50,  60,  70],
         [100, 110, 120],
         [150, 160, 170],
         [  0,   0, 250]],

        [[  0,  10,  20],
         [ 50,  60,  70],
         [100, 110, 120],
         [150, 160, 170],
         [  0,   0, 250]]], dtype=torch.int32)